# Generated by Django 6.0.3 on 2026-04-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contribuicaoopensource",
            name="nome_projeto",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="competencia",
            name="descricao",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="makingof",
            name="imagem",
            field=models.ImageField(blank=True, upload_to="portfolio/makingof"),
        ),
        migrations.AlterField(
            model_name="tecnologia",
            name="descricao",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="tecnologia",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="portfolio/tecnologias"
            ),
        ),
    ]
