# Generated by Django 6.0.3 on 2026-05-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_contribuicaoopensource_nome_projeto_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="makingof",
            name="portfolio",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tecnologia",
            name="portfolio",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
