# Generated by Django 6.0.3 on 2026-05-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_makingof_portfolio_tecnologia_portfolio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="makingof",
            name="erros",
            field=models.TextField(blank=True),
        ),
    ]
