# Generated by Django 6.0.3 on 2026-05-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_alter_makingof_erros"),
    ]

    operations = [
        migrations.AlterField(
            model_name="makingof",
            name="justificacao_opcoes",
            field=models.TextField(blank=True),
        ),
    ]
