# Generated by Django 6.0.3 on 2026-05-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artigos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artigo",
            name="data_criacao",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
