# Generated by Django 6.0.3 on 2026-05-16 14:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artigos", "0002_alter_artigo_data_criacao"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="artigo",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="artigos_likes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
